### PR TITLE
Error check msg should not be empty

### PR DESCRIPTION
**Pull request by alfredodeza**
This will now help get the actual error message out in logs. It wasn't being displayed before.

### CODE REVIEW

**Comment by alfredodeza** [comment]
@djgalloway to take full advantage of this, we will need a re-deploy. Not urgent, so we can wait to bundle up with something more critical?

**Comment by djgalloway** [comment]
@alfredodeza Sure.  Maybe bundle it with a pinning of gunicorn and pecan?

**Comment by alfredodeza** [comment]
I mean, "bundle" in, lets get those in other PRs, and deploy them at once. This is good to go as-is

**Comment by djgalloway** [comment]
> This is good to go as-is

OK.  I wasn't sure since the build failed.

**Pull request merged**
