### PR TITLE
ansible: nginx config for HTTPS

### PR DESCRIPTION
**Pull request by ktdreyer**
Add HTTPS to the chacra web server to protect authentication.

The key and certificate files are managed outside of Ansible.

### CODE REVIEW

**Comment by alfredodeza** [comment]
I think you would also need to add 443 to:
https://github.com/ceph/chacra/blob/dsc-repos/deploy/playbooks/roles/common/templates/nginx_site.conf#L2

**Comment by alfredodeza** [comment]
Maybe also try it out locally on a vagrant VM?

**Comment by ktdreyer** [comment]
Should we stop listening on port 80 entirely?

**Comment by ktdreyer** [comment]
Updated to stop listening on port 80, and use HTTPS only

**Pull request merged**
