### PR TITLE
Add Debian bullseye

### PR DESCRIPTION
**Pull request by djgalloway**
Signed-off-by: David Galloway <dgallowa@redhat.com>

### CODE REVIEW

**Review by andrewschoen — APPROVED** [review]

**Comment by dmick** [comment]
needs a ceph-build change

**Comment by djgalloway** [comment]
jenkins test

**Comment by dmick** [comment]
jenkins retest this please

**Comment by dmick** [comment]
jenkins retest this please

**Comment by dmick** [comment]
python-psycopg2 should be available

jenkins retest this please

**Comment by djgalloway** [comment]
```
root@adami07:~# apt-cache search python-psycopg2
python-psycopg2-doc - Python module for PostgreSQL (documentation package)
root@adami07:~# apt-cache search psycopg2
python-psycopg2-doc - Python module for PostgreSQL (documentation package)
python3-psycopg2 - Python 3 module for PostgreSQL
```

Sigh.  Will fix tomorrow.

**Comment by djgalloway** [comment]
@dmick https://github.com/ceph/ceph-build/pull/1904

**Comment by dmick** [comment]
jenkins retest this please

**Pull request merged**
