### PR TITLE
Revert "util,models/: include .ddeb when building deb repos"

### PR DESCRIPTION
**Pull request by alfredodeza**
Reverts ceph/chacra#267

I don't think we are ready for this, and there was no agreement if using a forked binary was the right approach. Reverting for now until we get consensus.

### CODE REVIEW

**Comment by alfredodeza** [comment]
I don't think we are discarding, but temporarily reverting so that we get a healthy system, and can get to some agreement on how to move forward.

**Comment by djgalloway** [comment]
Well, we have a working system at the moment.  Everything is functioning normally.. just with warnings.

Let's come to an agreement on how to move forward and get it done.

Does the special version just need to be compiled and `make install`ed?  Are we comfortable doing that with a repo we haven't vetted keeping in mind it touches all our binaries?

**Comment by tchaikov** [comment]
> It is more involved.

@alfredodeza 2 months ago, i hoped i could get the blessings and/or support from us. and i noted the plan A and plan B at https://github.com/ceph/ceph-build/pull/1367#issuecomment-522393725 . after the discussion with you over IRC, i learned that you wanted to hold this back, and that we needed to wait for Ken.

**Comment by ktdreyer** [comment]
My concern with forking reprepro is that someone on our team will need to watch that fork closely over the years. Someone will need to make sure that security fixes in upstream reprepro will also go into the forked reprepro. Who is going to do that, and for how long?

**Pull request closed without merging**
