### PR TITLE
Add 'bookworm' to known distros

### PR DESCRIPTION
**Pull request by dmick**

### CODE REVIEW

**Review by ljflores — APPROVED** [review]

**Comment by dmick** [comment]
jenkins retest please

**Comment by dmick** [comment]
retest

**Comment by dmick** [comment]
retest

**Comment by dmick** [comment]
retest

**Comment by dmick** [comment]
Two unrelated failures in the check, I'm going to ignore them for now (one was a random apt repo that failed, one is that braggi11 is running jammy and the code in the ansible to set the postgres version doesn't currently have a case for jammy)

**Pull request merged**
