### PR TITLE
deploy: preserve ceph-iscsi/master builds

### PR DESCRIPTION
**Pull request by dillaman**
Signed-off-by: Jason Dillaman <dillaman@redhat.com>

### CODE REVIEW

**Comment by alfredodeza** [comment]
@djgalloway I am not sure why this wasn't ever merged, I think it is deployed though right? (maybe not?)

@dillaman you aren't seeing disappearing builds for ceph-iscsi these days, are you?

**Comment by djgalloway** [comment]
Honestly don't remember if this got pushed.

**Comment by dillaman** [comment]
It only has 4 right now so it seems like it's not keeping the last 5 [1]

[1] https://shaman.ceph.com/repos/ceph-iscsi/

**Comment by dillaman** [comment]
@djgalloway I don't think this fix ever got pushed to the chacra nodes. It's still deleting the master branch refs. I just had to force rebuild since the last build from a couple weeks ago disappeared.

**Comment by djgalloway** [comment]
You're right; it didn't.  I'll take care of this today.

**Comment by djgalloway** [comment]
This is complete.

**Pull request merged**
