### PR TITLE
set is_updating to False when updating or recreating a repo

### PR DESCRIPTION
**Pull request by andrewschoen**
Signed-off-by: Andrew Schoen <aschoen@redhat.com>

### CODE REVIEW

**Comment by dmick** [comment]
is_updating is false when updating?  Eh?

Sent from Nine

**Comment by andrewschoen** [comment]
@dmick the ``async.poll_repos`` will ignore a repo that is currently being updated, to avoid a dogpile affect on celery. The tasks that actually make the repo set ``is_updating = True`` when they start the actual repo creation. See: https://github.com/ceph/chacra/blob/master/chacra/async/__init__.py#L105

**Comment by dmick** [comment]
OK, but, the commit message contradicts itself...if it's not actually updating, then your change has the effect of "Initialize is_updating to False until update actually starts".

**Comment by andrewschoen** [comment]
@dmick I'm setting is_updating to False so that these endpoints will have their desired effect which is set all the flags needed so that the celery task will pick up this repo and recreate it.

**Pull request merged**
